version: "3.9"
services:
  todo-lists:
    image: todo-lists
    ports:
      - "5000:5000"
    links:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
  mongodb:
    image: mongo:5.0.4
    ports:
      - "27017:27017"
