version: "3.9"
services:
  todos-lists-api:
    image: todos-lists-api
    ports:
      - "5100:5000"
    links:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
  mongodb:
    image: mongo:5.0.4
    ports:
      - "27017:27017"
