name: Main
on:
  push:
    branches:
      - "main"
  pull_request:
    types:
      - opened
    branches:
      - "main"

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture: "x64"
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Install editable package
        run: pip install -e .
      - name: Lint
        run: pylint $(git ls-files '*.py')
      - name: Test
        run: python -m pytest
