name: Main
on: [push, pull_request]

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Lint
        run: pylint $(git ls-files '*.py')
      - name: Test
        run: pytest